### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by d4l3k** [TreeHacks/slack-mentorship#2]
Hey!

I'm one of the developers working on the [nwHacks](https://nwhacks.io) hackathon. I'd love to be able to use a modified copy of slack-mentorship for our hackathon!

However, I've noticed that this project doesn't have a license mentioned in the README or a LICENSE file so the legality of us using it is questionable. 

Could you guys add a LICENSE so we can use it?

Thanks!

**Comment by RaphiePS** [comment]
Done! So amped that y'all are using it!
